# Generated by Django 4.2.2 on 2023-07-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='user_address2',
            field=models.CharField(max_length=255, verbose_name='address 2'),
        ),
    ]
