# Generated by Django 4.2.2 on 2023-07-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0003_alter_newuser_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='fullname',
            field=models.CharField(max_length=255, unique=True, verbose_name='Your Name / Business Name / Investors Name'),
        ),
    ]
