# Generated by Django 4.2.2 on 2023-07-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0004_alter_newuser_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='Email Address:'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='fullname',
            field=models.CharField(max_length=255, unique=True, verbose_name='Your Name, Business Name or Investors Name:'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_address',
            field=models.CharField(max_length=255, unique=True, verbose_name='address:'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_address2',
            field=models.CharField(max_length=255, verbose_name='address 2:'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_city',
            field=models.CharField(max_length=255, unique=True, verbose_name='city:'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_state',
            field=models.CharField(max_length=255, unique=True, verbose_name='state:'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_zipcode',
            field=models.CharField(max_length=10, unique=True, verbose_name='zipcode:'),
        ),
    ]
